BOARD_TAG    = mega2560
ARDUINO_PORT = /dev/cu.usbmodem1421

ARDUINO_LIBS = Ethernet Ethernet/utility SPI JeeLib HttpClient ArduinoPusherClient Time Wire Wire/utility DS1307RTC TimeAlarms

include /usr/local/arduino/Arduino.mk
